name: CI 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1
        with: 
          node-version: 18
      - name: install npm 
        run: npm install
      - name: Test
        run: npm run test:local
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0 
        if: failure()
        with: 
          name: logs 
          path: logs
